#!/bin/bash -e
sourcefile=$1
PACKAGE_CONF=x86_64-linux-ghc-7.8.4-packages.conf.d

upsearch () {
    DIR="$PWD"
    slashes=${DIR//[^\/]/}/
    directory="$DIR"
    for (( n=${#slashes}; n>0; --n ))
    do
        test -e "$directory/$1" && echo "$directory/$1" && return
        directory="$(dirname $directory)"
    done

    echo "" && return
}

#GHCOPTS="-Wall -fno-code -fno-warn-missing-signatures -XBangPatterns"
GHCOPTS="-Wall -fno-code -fno-warn-missing-signatures -no-user-package-db"

CabalDir=$(upsearch ".cabal-sandbox")


if "$CabalDir" == ""
then
    ghc $GHCOPTS $sourcefile &> /home/greg/output
else
    INCLUDES="-i$CabalDir/../src:$CabalDir/../dist/build/autogen:$CabalDir/../web:$CabalDir/../console"
    ghc $INCLUDES $GHCOPTS -package-conf="$CabalDir/$PACKAGE_CONF" "$sourcefile" #&> /home/greg/output
fi

if [[ -x `which hlint` ]]; then
    hlint $sourcefile
fi
